# -*- coding: utf-8 -*-

global KILL_MYSELF
global ACTIVATED
global GOOGLE_SERVICE 
global IS_GOOGLE_SERVICE_AUTHENTICATE
global CAL_EVENT_THREAD

KILL_MYSELF=0
ACTIVATED = False

GOOGLE_SERVICE= ''
IS_GOOGLE_SERVICE_AUTHENTICATED= False


